### ISSUE TITLE
name 'Piko' is not defined

### ISSUE THREAD

**Issue by feckert** [Tafkas/KostalPikoPy#3]
If I follow your example with pip i get always a traceback.

> raceback (most recent call last):
>   File "./costal.py", line 8, in <module>
>     p = Piko('192.168.1.99')
> NameError: name 'Piko' is not defined

What do i make wrong?

**Comment by Tafkas** [comment]
Could you post the content of your `costal.py` file?

**Comment by feckert** [comment]
I am using debian 9 (testing)
I have installed pikopy with `pip install --user pikopy`

`/usr/bin/env python` uses python 2.7.13
The content of my file is

> #!/usr/bin/env python
> import pikopy
> p = Piko('192.168.1.99')

`

**Comment by feckert** [comment]
I think we can close this :-)
